# Generated by Django 5.2.12 on 2026-04-10 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entreprise", models.CharField(max_length=200, verbose_name="entreprise")),
                (
                    "secteur",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech", "Informatique / Tech"),
                            ("finance", "Finance / Banque"),
                            ("sante", "Santé / Pharma"),
                            ("industrie", "Industrie"),
                            ("marketing", "Marketing / Communication"),
                            ("conseil", "Conseil"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="secteur",
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="site web")),
                ("lieu", models.CharField(blank=True, max_length=200, verbose_name="lieu / ville")),
                (
                    "teletravail",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("presentiel", "Présentiel"),
                            ("hybride", "Hybride"),
                            ("remote", "Full remote"),
                        ],
                        max_length=20,
                        verbose_name="télétravail",
                    ),
                ),
                ("poste", models.CharField(max_length=200, verbose_name="intitulé du poste")),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("stage", "Stage"),
                            ("alternance", "Alternance"),
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                        ],
                        default="stage",
                        max_length=20,
                        verbose_name="type de contrat",
                    ),
                ),
                (
                    "duree_contrat",
                    models.CharField(blank=True, max_length=100, verbose_name="durée"),
                ),
                (
                    "date_debut",
                    models.DateField(blank=True, null=True, verbose_name="date de début souhaitée"),
                ),
                (
                    "remuneration",
                    models.CharField(blank=True, max_length=100, verbose_name="rémunération"),
                ),
                ("lien_offre", models.URLField(blank=True, verbose_name="lien de l'offre")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoyee", "Envoyée"),
                            ("en_attente", "En attente"),
                            ("relancee", "Relancée"),
                            ("entretien", "Entretien"),
                            ("offre", "Offre reçue"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_candidature",
                    models.DateField(blank=True, null=True, verbose_name="date de candidature"),
                ),
                (
                    "date_relance",
                    models.DateField(blank=True, null=True, verbose_name="date de relance prévue"),
                ),
                (
                    "contact_nom",
                    models.CharField(blank=True, max_length=200, verbose_name="nom du contact"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="e-mail du contact"),
                ),
                (
                    "contact_linkedin",
                    models.URLField(blank=True, verbose_name="LinkedIn du contact"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes & remarques")),
                (
                    "lettre_motivation",
                    models.TextField(blank=True, verbose_name="lettre de motivation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-created_at"],
            },
        ),
    ]
