# Generated by Django 5.2.12 on 2026-04-10 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidatures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entretien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_entretien",
                    models.CharField(
                        choices=[
                            ("telephone", "Téléphonique"),
                            ("visio", "Visioconférence"),
                            ("presentiel", "Présentiel"),
                            ("technique", "Technique"),
                            ("rh", "RH"),
                            ("final", "Final / Direction"),
                        ],
                        default="telephone",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("passe", "Passé"),
                            ("annule", "Annulé"),
                            ("reporte", "Reporté"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("date_heure", models.DateTimeField(verbose_name="date et heure")),
                (
                    "duree_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="durée (minutes)"),
                ),
                (
                    "lieu_ou_lien",
                    models.CharField(blank=True, max_length=500, verbose_name="lieu ou lien visio"),
                ),
                (
                    "contact_nom",
                    models.CharField(blank=True, max_length=200, verbose_name="interlocuteur"),
                ),
                (
                    "contact_poste",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="poste de l'interlocuteur"
                    ),
                ),
                ("preparation", models.TextField(blank=True, verbose_name="notes de préparation")),
                (
                    "retour",
                    models.TextField(blank=True, verbose_name="retour / ressenti post-entretien"),
                ),
                (
                    "questions",
                    models.TextField(blank=True, verbose_name="questions posées / à préparer"),
                ),
                ("rappel_24h", models.BooleanField(default=True, verbose_name="rappel 24h avant")),
                ("rappel_1h", models.BooleanField(default=False, verbose_name="rappel 1h avant")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entretiens",
                        to="candidatures.candidature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entretiens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entretien",
                "verbose_name_plural": "Entretiens",
                "ordering": ["date_heure"],
            },
        ),
    ]
